extends Resource

class_name StationData

@export var stationData = {
	"1 - Azul": {
		"Jabaquara": 0,
		"Conceição": 0,
		"São Judas": 0,
		"Saúde": 0,
		"Praça da Árvore": 0,
		"Santa Cruz": 0,
		"Vila Mariana": 0,
		"Ana Rosa": 0,
		"Paraíso": 0,
		"Vergueiro": 0,
		"São Joaquim": 0,
		"Liberdade": 0,
		"Sé": 0,
		"São Bento": 0,
		"Luz": 0,
		"Tiradentes": 0,
		"Armênia": 0,
		"Portuguesa-Tietê": 0,
		"Carandiru": 0,
		"Santana": 0,
		"Jardim São Paulo-Ayrton Senna": 0,
		"Parada Inglesa": 0,
		"Tucuruvi": 0
	},
	"2 - Verde": {
		"Vila Prudente": 0,
		"Tamanduateí": 0,
		"Sacomã": 0,
		"Alto do Ipiranga": 0,
		"Santos-Imigrantes": 0,
		"Chácara Klabin": 0,
		"Ana Rosa": 0,
		"Paraíso": 0,
		"Brigadeiro": 0,
		"Trianon-Masp": 0,
		"Consolação": 0,
		"Clínicas": 0,
		"Santuário Nossa Senhora de Fátima-Sumaré": 0,
		"Vila Madalena": 0
	},
	"3 - Vermelha": {
		"Corinthians-Itaquera": 0,
		"Artur Alvim": 0,
		"Patriarca-Vila Ré": 0,
		"Guilhermina-Esperança": 0,
		"Vila Matilde": 0,
		"Penha": 0,
		"Carrão-Assaí Atacadista": 0,
		"Tatuapé": 0,
		"Belém": 0,
		"Bresser-Mooca": 0,
		"Brás": 0,
		"Pedro II": 0,
		"Sé": 0,
		"Anhangabaú": 0,
		"República": 0,
		"Santa Cecília": 0,
		"Marechal Deodoro": 0,
		"Palmeiras-Barra Funda": 0
	},
	"4 - Amarela": {
		"Vila Sônia": 0,
		"São Paulo-Morumbi": 0,
		"Butantã": 0,
		"Pinheiros": 0,
		"Faria Lima": 0,
		"Paulista": 0,
		"Higienópolis-Mackenzie": 0,
		"República": 0,
		"Luz": 0
	},
	"5 - Lilás": {
		"Capão Redondo": 0,
		"Campo Limpo": 0,
		"Vila das Belezas": 0,
		"Giovanni Gronchi": 0,
		"Santo Amaro": 0,
		"Largo Treze": 0,
		"Adolfo Pinheiro": 0,
		"Alto da Boa Vista": 0,
		"Borba Gato": 0,
		"Brooklin": 0,
		"Campo Belo": 0,
		"Eucaliptos": 0,
		"Moema": 0,
		"AACD-Servidor": 0,
		"Hospital São Paulo": 0,
		"Santa Cruz": 0,
		"Chácara Klabin": 0
	},
	"7 - Rubi": {
		"Luz": 0,
		"Palmeiras-Barra Funda": 0,
		"Água Branca": 0,
		"Lapa": 0,
		"Piqueri": 0,
		"Pirituba": 0,
		"Vila Clarice": 0,
		"Jaraguá": 0,
		"Vila Aurora": 0,
		"Perus": 0,
		"Caieiras": 0,
		"Franco da Rocha": 0,
		"Baltazar Fidelis": 0,
		"Francisco Morato": 0,
		"Botujuru": 0,
		"Campo Limpo Paulista": 0,
		"Várzea Paulista": 0,
		"Jundiaí": 0
	},
	"8 - Diamante": {
		"Júlio Prestes": 0,
		"Palmeiras-Barra Funda": 0,
		"Lapa": 0,
		"Domingos de Moraes": 0,
		"Imperatriz Leopoldina": 0,
		"Presidente Altino": 0,
		"Osasco": 0,
		"Comandante Sampaio": 0,
		"Quitaúna": 0,
		"General Miguel Costa": 0,
		"Carapicuíba": 0,
		"Santa Terezinha": 0,
		"Barueri": 0,
		"Jardim Belval": 0,
		"Jardim Silveira": 0,
		"Jandira": 0,
		"Sagrado Coração": 0,
		"Engenheiro Cardoso": 0,
		"Itapevi": 0,
		"Santa Rita": 0,
		"Amador Bueno": 0
	},
	"9 - Esmeralda": {
		"Osasco": 0,
		"Presidente Altino": 0,
		"Ceasa": 0,
		"Villa-Lobos–Jaguaré": 0,
		"Cidade Universitária": 0,
		"Pinheiros": 0,
		"Hebraica-Rebouças": 0,
		"Cidade Jardim": 0,
		"Vila Olímpia": 0,
		"Berrini": 0,
		"Morumbi": 0,
		"Granja Julieta": 0,
		"João Dias": 0,
		"Santo Amaro": 0,
		"Socorro": 0,
		"Jurubatuba": 0,
		"Autódromo": 0,
		"Interlagos": 0,
		"Grajaú": 0,
		"Primavera-Interlagos": 0,
		"Mendes-Vila Natal": 0,
		"Varginha": 0
	},
	"10 - Turquesa": {
		"Brás": 0,
		"Juventus-Mooca": 0,
		"Ipiranga": 0,
		"Tamanduateí": 0,
		"São Caetano do Sul - Prefeito Walter Braido": 0,
		"Utinga": 0,
		"Prefeito Saladino": 0,
		"Santo André - Prefeito Celso Daniel": 0,
		"Capuava": 0,
		"Mauá": 0,
		"Guapituba": 0,
		"Ribeirão Pires": 0,
		"Rio Grande da Serra": 0
	},
	"11 - Coral": {
		"Luz": 0,
		"Brás": 0,
		"Tatuapé": 0,
		"Corinthians-Itaquera": 0,
		"Dom Bosco": 0,
		"José Bonifácio": 0,
		"Guaianases": 0,
		"Antonio Gianetti Neto": 0,
		"Ferraz de Vasconcelos": 0,
		"Poá": 0,
		"Calmon Viana": 0,
		"Suzano": 0,
		"Jundiapeba": 0,
		"Brás Cubas": 0,
		"Mogi das Cruzes": 0,
		"Estudantes": 0
	},
	"12 - Safira": {
		"Brás": 0,
		"Tatuapé": 0,
		"Engenheiro Goulart": 0,
		"USP Leste": 0,
		"Comendador Ermelino": 0,
		"São Miguel Paulista": 0,
		"Jardim Helena - Vila Mara": 0,
		"Itaim Paulista": 0,
		"Jardim Romano": 0,
		"Engenheiro Manoel Feio": 0,
		"Itaquaquecetuba": 0,
		"Aracaré": 0,
		"Calmon Viana": 0
	},
	"13 - Jade": {
		"Engenheiro Goulart": 0,
		"Guarulhos - Cecap": 0,
		"Aeroporto-Guarulhos": 0
	},
	"15 - Prata": {
		"Vila Prudente": 0,
		"Oratório": 0,
		"São Lucas": 0,
		"Camilo Haddad": 0,
		"Vila Tolstói": 0,
		"Vila União": 0,
		"Jardim Planalto": 0,
		"Sapopemba": 0,
		"Fazenda da Juta": 0,
		"São Mateus": 0,
		"Jardim Colonial": 0
	},
	"17 - Ouro": {
		"Morumbi": 0,
		"Chucri Zaidan": 0,
		"Vila Cordeiro": 0,
		"Campo Belo": 0
	}
}

func report(data) -> void:
	stationData[data[0]][data[1]] += 1
