extends OptionButton

@onready var placeholder = $Placeholder

func _ready():
	self.disabled = true
	self.clip_text = true


func _on_botao_item_selected(index: int) -> void:
	self.disabled = false
	var popup = self.get_popup()
	popup.max_size = Vector2(400, 150)
	
	placeholder.text = ""
	
	var n = index
	
	for i in range(self.item_count):
		self.remove_item(0)
	
	if(n == 0): #Linha 1
		self.add_item("Jabaquara")
		self.add_item("Conceição")
		self.add_item("São Judas")
		self.add_item("Saúde (Ultrafarma)")
		self.add_item("Praça da Árvore")
		self.add_item("Vila Mariana")
		self.add_item("Ana Rosa")
		self.add_item("Paraíso")
		self.add_item("Vergueiro")
		self.add_item("São Joaquim")
		self.add_item("Japão - Liberdade")
		self.add_item("Sé")
		self.add_item("São Bento")
		self.add_item("Luz")
		self.add_item("Tiradentes")
		self.add_item("Armênia")
		self.add_item("Portuguesa - Tietê")
		self.add_item("Carandiru")
		self.add_item("Santana")
		self.add_item("Jardim São Paulo")
		self.add_item("Parada Inglesa")
		self.add_item("Tucuruvi")
	
	elif(n == 1): #Linha 2
		self.add_item("Vila Prudente")
		self.add_item("Tamanduateí")
		self.add_item("Sacomã")
		self.add_item("Alto do Ipiranga")
		self.add_item("Santos-Imigrantes")
		self.add_item("Chácara Klabin")
		self.add_item("Ana Rosa")
		self.add_item("Paraíso")
		self.add_item("Brigadeiro")
		self.add_item("Trianon-Masp")
		self.add_item("Consolação")
		self.add_item("Clínicas")
		self.add_item("N. Sra. de Fátima")
		self.add_item("Vila Madalena")

	elif(n == 2): #Linha 3
		self.add_item("Corinthians-Itaquera")
		self.add_item("Artur Alvim")
		self.add_item("Patriarca-Vila Ré")
		self.add_item("Guilhermina-Esperança")
		self.add_item("Vila Matilde")
		self.add_item("Penha-Lojas Besni")
		self.add_item("Carrão-Assaí Atacadista")
		self.add_item("Tatuapé")
		self.add_item("Belém")
		self.add_item("Bresser-Mooca")
		self.add_item("Brás")
		self.add_item("Pedro II")
		self.add_item("Sé")
		self.add_item("Anhangabaú")
		self.add_item("República")
		self.add_item("Santa Cecília")
		self.add_item("Marechal Deodoro")
		self.add_item("Palmeiras-Barra Funda")

	elif(n == 3): #Linha 4
		self.add_item("Luz")
		self.add_item("República")
		self.add_item("Higienóplolis - Mackenzie")
		self.add_item("Paulista")
		self.add_item("Oscar Freire")
		self.add_item("Fradique Coutinho")
		self.add_item("Faria Lima")
		self.add_item("Pinheiros")
		self.add_item("Butantã")
		self.add_item("São Paulo - Morumbi")
		self.add_item("Vila Sõnia")

	elif(n == 4): #Linha 5
		self.add_item("Capão Redondo")
		self.add_item("Campo Limpo")
		self.add_item("Vila das Belezas")
		self.add_item("Giovanni Gronchi")
		self.add_item("Santo Amaro")
		self.add_item("Largo Treze")
		self.add_item("Adolfo Pinheiro")
		self.add_item("Alto da Boa Vista")
		self.add_item("Borba Gato")
		self.add_item("Brooklin")
		self.add_item("Campo Belo")
		self.add_item("Eucaliptos")
		self.add_item("Moema")
		self.add_item("AACD - Servidor")
		self.add_item("Hospital São Paulo")
		self.add_item("Santa Cruz")
		self.add_item("Chácara Klabin")
		
	elif(n == 5): #Linha 7
		self.add_item("Luz")
		self.add_item("Palmeiras- BarraFunda")
		self.add_item("Água Branca")
		self.add_item("Lapa")
		self.add_item("Piqueri")
		self.add_item("Pirituba")
		self.add_item("Vila Clarice")
		self.add_item("Jaraguá")
		self.add_item("Perus")
		self.add_item("Caieiras")
		self.add_item("Franco da Rocha")
		self.add_item("Franco da Rocha")
		self.add_item("Baltazar Fidélis")
		self.add_item("Francisco Morato")
		self.add_item("Botujuru")
		self.add_item("Campo Limpo Paulista")
		self.add_item("Várzea Paulista")
		self.add_item("Jundiaí")
		
	elif(n == 6): #Linha 8 
		self.add_item("Júlio Prestes")
		self.add_item("Palmeiras - Barra Funda")
		self.add_item("Lapa")
		self.add_item("Domingos de Moraes")
		self.add_item("Imperatriz Leopoldina")
		self.add_item("Presidente Altino")
		self.add_item("Osasco")
		self.add_item("Comandante Sampaio")
		self.add_item("Quitaúna")
		self.add_item("General Miguel Costa")
		self.add_item("Carapicuíba")
		self.add_item("Santa Terezinha")
		self.add_item("Antônio João")
		self.add_item("Barueri")
		self.add_item("Jardim Belval")
		self.add_item("Jardim Silveira")
		self.add_item("Jandira")
		self.add_item("Sagrado Coração")
		self.add_item("Itapevi")
		self.add_item("Engenheiro Cardoso")
		self.add_item("Amador Bueno")
		
	elif(n == 7): #Linha 9
		self.add_item("Osasco")
		self.add_item("Presidente Altino")
		self.add_item("Ceasa")
		self.add_item("Villa-Lobos - Jaguaré")
		self.add_item("Cidade Universitária")
		self.add_item("Pinheiros")
		self.add_item("Hebraica - Rebouças")
		self.add_item("Cidade Jardim")
		self.add_item("Vila Olímpia")
		self.add_item("Berrini")
		self.add_item("Morumbi")
		self.add_item("Granja Julieta")
		self.add_item("João Dias")
		self.add_item("Santo Amaro")
		self.add_item("Socorro")
		self.add_item("Jurubatuba")
		self.add_item("Autódromo")
		self.add_item("Primavera - Interlagos")
		self.add_item("Grajaú")
		self.add_item("Mendes - Vila Natal")
		self.add_item("Varginha")
		
	elif(n == 8): #Linha 10
		self.add_item("Brás")
		self.add_item("Juventus - Mooca")
		self.add_item("Ipiranga")
		self.add_item("Tamanduateí")
		self.add_item("São Caetano do Sul - Prefeito Walter Braido")
		self.add_item("Utinga")
		self.add_item("Prefeito Saladino")
		self.add_item("Santo André")
		self.add_item("Capuava")
		self.add_item("Mauá")
		self.add_item("Guapituba")
		self.add_item("Ribeirão Pires")
		self.add_item("Rio Grande da Serra")
		
	elif(n == 9): #Linha 11
		self.add_item("Luz")
		self.add_item("Brás")
		self.add_item("Tatuapé")
		self.add_item("Corinthians-Itaquera")
		self.add_item("Dom Bosco")
		self.add_item("José Bonifácio")
		self.add_item("Guaianases")
		self.add_item("Antônio Gianetti Neto")
		self.add_item("Ferraz de Vasconcelos")
		self.add_item("Poá")
		self.add_item("Calmon Viana")
		self.add_item("Suzano")
		self.add_item("Jundiapeba")
		self.add_item("Brás Cubas")
		self.add_item("Mogi das Cruzes")
		self.add_item("Estudantes")
		
	elif(n == 10): #Linha 12
		self.add_item("Brás")
		self.add_item("Tatuapé")
		self.add_item("Engenheiro Goulart")
		self.add_item("USP Leste")
		self.add_item("Comendador Ermelino")
		self.add_item("São Miguel Paulista")
		self.add_item("Jardim Helena - Vila Mara")
		self.add_item("Itaim Paulista")
		self.add_item("Jardim Romano")
		self.add_item("Engenheiro Manoel Feio")
		self.add_item("Itaquaquecetuba")
		self.add_item("Aracaré")
		self.add_item("Calmon Viana")
		
	elif(n == 11): #Linha 13
		self.add_item("Engenheiro Goulart")
		self.add_item("Guarulhos - Cecap")
		self.add_item("Aeroporto - Guarulhos")
	
	elif(n == 12): #Linha 15
		self.add_item("Vila Prudente")
		self.add_item("Oratório")
		self.add_item("São Lucas")
		self.add_item("Camilo Haddad")
		self.add_item("Vila Tolstói")
		self.add_item("Vila União")
		self.add_item("Jardim Planalto")
		self.add_item("Sapopemba")
		self.add_item("Fazenda da Juta")
		self.add_item("São Mateus")
		self.add_item("Jardim Colonial")
